import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { GoGenGeneratedModule, GoGenGeneratedSharedModule } from './generated/module.js';
import { GoGenValidator, registerValidationChecks } from './go-gen-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type GoGenAddedServices = {
    validation: {
        GoGenValidator: GoGenValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type GoGenServices = LangiumServices & GoGenAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const GoGenModule: Module<GoGenServices, PartialLangiumServices & GoGenAddedServices> = {
    validation: {
        GoGenValidator: () => new GoGenValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createGoGenServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    GoGen: GoGenServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        GoGenGeneratedSharedModule
    );
    const GoGen = inject(
        createDefaultModule({ shared }),
        GoGenGeneratedModule,
        GoGenModule
    );
    shared.ServiceRegistry.register(GoGen);
    registerValidationChecks(GoGen);
    return { shared, GoGen };
}
