services:
  scg-client:
    container_name: scg-client
    build:
      context: scg-client
    volumes:
      - "${PWD}/scg-client/:/app"
  scg-api:
    container_name: scg-api
    build:
      context: scg-api
    ports:
      - "8000:8000"
    depends_on:
      - scg-db
    hostname: scg-api
    volumes:
      - "${PWD}/scg-api/:/app"
    environment:
      ENV: dev
  scg-db:
    container_name: scg-db
    image: postgres:12
    ports:
      - "5432:5342"
    volumes:
      - scg-db-data:/var/lib/postgresql/data
    hostname: scg-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scg
  denatran-fake-api:
    container_name: denatran-fake-api
    build:
      context: denatran-fake-api
    ports:
      - "8001:8000"
    depends_on:
      - scg-db
    hostname: denatran-fake-api
    volumes:
      - "${PWD}/denatran-fake-api/:/app"
    environment:
      ENV: dev
volumes:
  scg-db-data:
